version: 2
jobs:
  doc-build:
    # use pre-built image, see: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      # gets the branch code for you to work with in subsequent steps
      - checkout
      - run:
          name: prep environment & make docs
          # list of shell commands to prepare environment and build doc
          command: |
            python3 -m venv doc-env
            . doc-env/bin/activate
            pip install -r requirements_doc.txt --progress-bar off
            pip install .
            cd docs
            make html
      # store built documentation files as artifact
      - store_artifacts:
          path: doc/_build/html
# simple workflow with one job
# see: https://circleci.com/docs/2.0/config-intro/#part-four-approved-to-start
workflows:
  version: 2
  push:
    jobs:
      - doc-build
