name: "Build documentation"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: docs
    # This step uses ammaraskar's Sphinx Build Action: https://github.com/ammaraskar/sphinx-action
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        # list of shell commands to prepare environment before build
        pre-build-command: "pip install -r docs/requirements.txt && pip install ."
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name == 'push'
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html
