name: "Build documentation"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # This step uses ammaraskar's Sphinx Build Action: https://github.com/ammaraskar/sphinx-action
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        # list of shell commands to prepare environment before build
        pre-build-command: "pip install -r requirements_doc.txt && pip install ."
    # Create an artifact of the html output using Github action: https://github.com/actions/upload-artifact
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
